### ISSUE TITLE
Can't insert svg in IE9

### ISSUE THREAD

**Issue by mcmimik** [Keyamoon/svgxuse#19]
Very simple example: http://mcmimik.ru/test/svgxuse-01.html
Script can't inject svg sprites in IE9.
But it successfully downloads it: http://mcmimik.ru/i/few2i.png

**Comment by Matthieusch** [comment]
Hi @mcmimik!
I had the same problem with Apache server.
Don't know if that can help you, but here is the solution which worked for me :

`XDomainRequest: The requested URL's server must have the Access-Control-Allow-Origin header set to either all ("*") or to include the origin of the request.`

Here is my `.htacess` file content:

```
# Add headers to all responses.
<IfModule mod_headers.c>
  Header set Access-Control-Allow-Origin *
</IfModule>
```

Hope it'll help!

**Comment by Keyamoon** [comment]
It turns out `XDomainRequest` requires CORS headers to be set, even when the request is not cross domain.

v1.1.17 fixes this IE9 issue by checking whether the request is cross domain. It uses `XDomainRequest` only when necessary. `XMLHttpRequest` works fine in IE9 in other cases.

@mcmimik Thank you for reporting this issue. Please try the latest version. It should fix the issue.

**Comment by mcmimik** [comment]
Thank you a lot! Super fast fix!
