### ISSUE TITLE
Huge performance issue on IE

### ISSUE THREAD

**Issue by webmatrixxxl** [Keyamoon/svgxuse#20]
Hi man I was using your lib on my project but i notice performance issue on IE(10, 11, edge) on different machines.

My UI was unresponsive and very laggy so I try svg4everybody.js it was much better.

**Comment by Keyamoon** [comment]
Can you provide a reduced test case?

**Comment by webmatrixxxl** [comment]
Here is link temporary link: URL removed

As I investigate further the problem is in crappy IE svg rendering, but still getting better frame rate with svg4everybody.js. 

I don't see any difference between using  svg4everybody.js and <use> without absolute path so svg4everybody.js isn't causing any additional performance issue in my case.
.

**Comment by webmatrixxxl** [comment]
You can compare performance with svg4everybody here URL removed

**Comment by Keyamoon** [comment]
Thanks. As you hinted yourself, it seems that IE has some performance issues when rendering SVG elements with `use` elements. I made [another test case](https://dl.dropboxusercontent.com/u/38300086/svgxuse-issue20-test/index.html) based on yours, which embeds those SVG definitions (in your `shapes.svg` file) in the html itself, and I removed svgxuse from your js. The page is still slow in IE. So it's not an issue with svgxuse, but IE itself.

svg4everybody replaces all `use` elements with the contents of the SVG definition and therefore avoids this issue. Since svgxuse is a polyfill, it's not supposed to replace `use` elements. It simply makes it possible to use SVGs with `use` elements that reference external SVGs.
