### ISSUE TITLE
polyfill runs when it shouldn't

### ISSUE THREAD

**Issue by thomasmattheussen** [Keyamoon/svgxuse#9]
I added the polyfill for IE and Edge but I noticed that the polyfill also ran (and injected the svg) on browsers where it shouldn't (chrome, firefox). These browsers displayed the svg use elements fine without the polyfill.

**Comment by Keyamoon** [comment]
The polyfill would run, but it shouldn't be injecting the SVG if not needed. I don't see this issue in the [demo page](https://icomoon.io/svgxuse-demo/). Can you provide a reduced test case?

**Comment by Keyamoon** [comment]
I was able to reproduce this issue with `<use>` elements that get added dynamically. It seems to only happen when the SVG being referenced hasn't been cached. This is because the polyfill goes through all `<use>` elements. If it finds them empty, it sends a request. SVGs that haven't been cached take some time to load and therefore the polyfill sends the request.

**Comment by thomasmattheussen** [comment]
Hmm, my use elements don't get added dynamically... So not sure if that's also my problem. (I do have cache disabled though, so that may be related?)

I'll try to make a reduced test case asap

**Comment by thomasmattheussen** [comment]
Could it be that they don't get added dynamically but are inside a div that has display: none? I seem to have narrowed it down to this being the problem in my case.

**Comment by Keyamoon** [comment]
svgxuse was updated to ignore hidden `use` elements until they become visible. Please try v1.1.5 to see if it fixes the issue in your case.

**Comment by thomasmattheussen** [comment]
why, yes it does! thanks again! ;)

**Comment by Keyamoon** [comment]
Thank you, for reporting this issue.
